
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # основной порт
      - "15672:15672"   # UI для админки
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - contract_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
    - contract_network

  web:
    image: ${DOCKERHUB_USERNAME}/contract-backend:${TAG}
    container_name: contract
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      gunicorn -c gunicorn.conf.py run:app
    networks:
      - contract_network

  scheduler:
    image: ${DOCKERHUB_USERNAME}/contract-backend:${TAG}
    container_name: scheduler
    restart: always
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      python schedule_run.py
    networks:
      - contract_network

networks:
  contract_network:
    external: true
