
services:

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
    - contract_network

  web:
    image: ${DOCKERHUB_USERNAME}/contract-service:${TAG}
    container_name: contract
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      gunicorn -c gunicorn.conf.py run:app
    networks:
      - contract_network


networks:
  contract_network:
    external: true
